## Assignment 1: Creation and indexing

- Create a numpy array x with the elements [2,5,12,18] and dtype float64. print length and dtype.
- Implement a function called "mean" which computes the mean of the elements of a given numpy array x using a for loop and indexing of elements. 


In [ ]:
import numpy as np
import math


In [33]:
#implement here
arr_1 = np.array([2,5,12,18], dtype= "float64")
print(arr_1)

def my_mean(arr):
    sum = 0 
    for i in arr:
        sum = sum + i
    return sum/len(arr)

print("Mean: ", my_mean(arr_1))


[ 2.  5. 12. 18.]
Mean:  9.25


## Assignment 2: Multidimensional arrays

- print len and shape of A.
- use your function mean above and a for loop to print the mean of each column of A
- compute the trace of A (sum of diagonal elements) without using np.trace. you can try to use mean for this as well! Compare to the result of np.trace!

In [40]:
A=np.random.randn(4,5)
print(np.shape(A))

for i in range(np.shape(A)[0]):
    mean = my_mean(A[i,:])
    print("Mean: of column", i, ": ", mean)

# it's not a "true" diagonal since the matrix is not square
diag = np.zeros(np.shape(A)[0])
for i in range(np.shape(A)[0]):
    for j in range(np.shape(A)[1]):
        if i == j:
            diag[i] = A[i,j]

print("Diagonal : ", diag)
print("Mean of diagonal: ", my_mean(diag))


(4, 5)
Mean: of column 0 :  0.16109094507112504
Mean: of column 1 :  0.4780538831588929
Mean: of column 2 :  0.34507407860849754
Mean: of column 3 :  0.1232914158529363
Diagonal :  [-0.24528935 -0.51676563  0.38667448 -0.96214035]
Mean of diagonal:  -0.3343802133275236


## Assignment 3: Writing to an array

- implement a function identity(N) that returns the NxN identity matrix without using np.eye.
- Hint: you can create a zero-matrix and then use indexing to write to the diagonal elements

In [41]:
def identity(N : int) -> np.ndarray:
    arr = np.zeros((4,4))
    for i in range(N):
        for j in range(N):
            if i == j:
                arr[i,j] = 1
    return arr
identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Assignment 4: Simple Math

- implement the function relative_error(x,y) that for an arbitrary array computes the elementwise relative error between the elements of x and y, defined as:
  $$ E=\frac{|x-y|}{|y|}$$

In [55]:
def relative_error(x,y):
    e = 0
    for i in range(len(y)):
        print(y[i])
        if y[i] == 0.0:
            raise AssertionError("Error: Division by zero")
        else:
            e = e + abs((x[i]-y[i])/y[i])
    return e

x=np.array([1.0,2.0,3.0,4.0])
y=np.array([2.0,2.0,4.0,5.0])
print(relative_error(x,y))

2.0
2.0
4.0
5.0
0.95


## Assignment 5: Relational Operators & Fancy Indexing

- implement the function all_errors_small(x,y,threshold) that returns true if the relative error of all elements of x and y are smaller than the threshold value.
- using relational operators and fancy indexing, print out the x and y values that exceed 0.2

In [6]:
def all_errors_small(x,y,threshold):
    return np.all(relative_error(x,y)<threshold)
print(all_errors_small(x,y,1.0)) #expects True
print(all_errors_small(x,y,0.1)) #expects False

#implement the second part
#your code here!

True
True


## Assignment 6: Linear Algebra
We give two choices here, that you can pick based on your linear algebra knowledge. 6.1 is a matrix square root and 6.2 a least squares fit.
### 6.1 Matrix Square roots

Implement the matrix square root function sqrtm(A) for square positive definite matrices A.
It is defined the following way: Let 
$A=U D U^T$ be the eigen decomposition of A where U is the matrix with the eigenvectors of A in the columns and D is the diagonal matrix with the eigenvalues on the diagonal. Then the square root $S=U D^{1/2} U^T$ where $D^{1/2}$ is the elementwise square root of $D$.

Verify correctness of your implementation by checking that $A=S S$. You can use all_errors_small for this.

Hint: np.diag can create D. 

In [7]:
def sqrtm(A):
    return 0#your code here!
#creation of a positive definite A
A=np.random.randn(4,4)
A=A@A.T
S=sqrtm(A)
#implement the correctness check below
#your code here!



### 6.2 Least Squares Fit / Linear Regression
We will implement a least squares fit. For a set of data $X$ where each row stores a point $x_i$, and a set of measurements $y$ where $y_i$ is the measurement of $x_i$, we want to find the linear function $f(x)=w^Tx$ such that for a given $x_i$, $f(x_i)\approx y_i$.

Your task is to implement the computation of the weights that minimize the mean squared error $w=(X^TX)Xy$ as well as implement the computation of the noisy labels. The data points are generated as $y_i= w^Tx_i+\epsilon_i$ where $\epsilon_i$ is standard normally distributed noise. Note that when computing this for all points in $X$ simultaneously without using loops, you need to compute $y=Xw+\epsilon$

At the end of this day you can try to plot the predictions of the model together with a scatter plot of the data points and compare that to the true model


In [8]:
# A little help for X.
# We want to sample a simple 1D problem with 50 points.
# we add a second column that is constant 1,which allows us to learn a constant offset parameter. 
# Thus we actually compute f(x)=w[0]x+w[1]
X = 10*np.random.randn(50,2) #50 points with 2 values each
X[:,-1] = 1 #overwrite the last column (using -1 here instead of "1" allows us to change the dimensionality of the data!)
w_truth = np.array([2.0,3.0]) #the true unknown values
#Subtask 1: compute y
# for this first generate a normal distributed vector epsilon with 20 entries
# then compute y_i= w^Tx_i+epsilon_i (
epsilon=0 #your code here!
y = 0 #your code here!

#Subtask 2: compute w
w=0 #your code here!

## Assignment 7: Reductions
Pick one:

1. Using np.mean implement the function variance(x) that computes the variance of the elements of x. The variance is defined as:
$$ var = mean[x^2]-mean[x]^2$$
where $mean[\cdot]$ is the mean operator for the argument $x$. Compare your results to np.var.
2. If you have solved 6.2 you can also compute the mean squared error $mean[(f(x)-y)^2]$ between the prediction of your model and the observed values.
3. Advanced: you can use np.argmin(x) which returns the index of the smallest element of x. Use that together with np.var to print for a given matrix A the column with smallest variance.

In [9]:
#1.
def variance(x):
    return 0#your code here!
x=np.random.randn(1000)
variance(x)

0

In [ ]:
#advanced 

A=np.random.randn(4,4)
print(A)
s
#implement it here
index = 0 #your code here!
print(A[:,index])

[[ 1.15316866  0.97968848  1.08193934  0.3157531 ]
 [ 2.26887898 -0.0350948   0.61426188 -0.1124257 ]
 [-0.62865152 -0.61444815 -0.2756239   0.23296138]
 [ 0.88254244 -0.50556832  0.35374391  0.29435624]]
[ 1.15316866  2.26887898 -0.62865152  0.88254244]


# Assignment 8: Plotting data

Load the iris.csv file. Each row contains five columns. The last column stores labels (0,1,2).
Separate the array using slicing to get one array x with the first two columns and an array y with the last column. 

Use fancy indexing and relations to split x into two arrays where one array contains all rows of x for which y=0, and the other the ones for which y>0.

use plt.scatter to print both arrays as point clouds, choose marker size and point color

add a legend for both point clouds. 

add axis descriptions: "sepal length" on x-axis and "sepal width" on y-axis.

finally, ensure a nice figure size with enough dpi and save the png on disk

In [11]:
#your code here!

## Ideas for advanced tasks:

1. You can try to implement sampling from a multivariate normal distribution with mean m and covariance matrix C. This is done via $x=m+S\epsilon$ where $S$ is the matrix square root of C and $\epsilon$ is a normal distributed vector. You have implemented the square root already. You will need to look at broadcasting for this.
2. Solve 6.2 if you haven't already and add a nice plot of the data, your computed predictions and the line of the true value.
3. Implement a function that takes a 2D array of points and normalizes the columns to mean 0 and variance 1. You can use it to normalize the dataset in Assignment 8.
4. Pick the very advanced task below if you are up for a challenge!

## Challenge! Implement a simulation of the N-body problem!

The N-body problem is at its core a simple task: we have a number of point-masses, for example planets, stars etc, with a very large mass and very small radius compared to their distance to each other. Gravity will pull each of the planets together and thus they begin to move and orbit each other. A mathematical description of the N-body system is easy, but a simulation is actually hard. 

For simplicity we look at the N-body problem in 2D. Such a system is for example given by the solar system, where most planets nicely sit on plane around the sun and we can just look from above on it.

At a given time t, we model the positions and velocities of then ith planet/star etc as a vector of positions $p_i$ with velocity $v_i$ and mass $m_i$. Since physically, velocity is the derivative of the position wrt time, we can approximate the movement of a planet during time $\Delta_t$ as $p_i+\Delta_t v_i$. The true complexity lies in the change of $v_i$ which is defined as its derivative wrt time:

$$ \frac{\partial}{\partial t}v_i=G\sum_{j=1, j\neq i}^N m_j \frac{p_j - p_i}{(p_j - p_i)^3+\epsilon}$$

Here $G$ is the gravitational constant, $N$ the number of objects. $\epsilon>0$ is a number not derived from mathematics but a constant added for numerical reasons, to prevent division by 0 when the distance of $p_i$ and $p_j$ is approximately 0. 

Instead of heaving a vector per planet, we will merge the velocities and positions matrices  $p_t,v_t$ indexed by the current time index $t$, where each row represents one planet. With this, we can simulate the solar system over time as

$$ v_{t+1}=v_t+\Delta t \frac{\partial}{\partial t}v_t$$
$$ p_{t+1}=p_t+\Delta t v_{t+1}$$

Please note that we use $v_{t+1}$ in the second step. This is very important to get a good simulation (the resulting scheme is a so-called symplectiv Euler integration, that aims to keep the total energy of the system constant)

Thus, your task is the following:
1. Implement the derivative. Aim to do this without using any loops. For this check "broadcasting" in the notes and on the web.
   If this is hard at the beginning, try to only use a single loop and remove that one in the second step! implement the norm yourself or use np.linalg.norm
2. Implement the symplectic integrator over $T$ steps with a given time step $\Delta_t$ starting from an initial value for both $p$ and $v$.
   Store for each time step the resulting matrices $v_{t+1}$ and $p_{t+1}$ in a 3D array.
4. Plot the results! begin by plotting the paths of the objects. compute the average speed of the planets (speed is the norm of $|v_i|$)
   and plot the speed of earth and jupyter as function of time. You can also try to plot the velocity vector direction by drawing small arrows along the plotted orbits. For this, look up the docs of matplotlib.pyplot.quiver https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html In general use this opportunity to familiarize yourself with more functions in matplotlib. Can you make the plot square so that circles become true circles?

We have provided a reasonable setting for the earth,sun and jupiter system. Aim to simulate the system for 12 years at a resolution of 1h per step. This is the orbit time of jupiter. This system is reasonably simple to compute. Unfortunately the simple integrator we use does not work very well for more complex system. If you are willing to invest more effort and time in it, you can try to simulate the earth-sun-moon system. However, be careful to not shoot the moon out of the solar system :-)



In [12]:
#Settings

G=6.67430e-11 #gravitational constant
year=365*24*60*60 #number of seconds in a year
dt=60*60 #time step 1h
#number of simulation steps
steps=int(12*year/dt) #for testing choose this as 5 steps or so. 12 years are one orbit of jupiter

#earth,sun,jupiter
#masses in kg
m=np.array([5.972e24,1.9891e30,1.9e27])
#initial positions in m. each row is one position vector of earth, sun,jupiter
#values are derived based on average distance of the planets from the sun.
#we initialize all of them in a line along the x-axis.
p_init=np.array([[149.0e9,0.0],[0.0,0.0],[790.0e9,0.0]])
#initial velocity in  m/s. Given the position of the planets relative to the sun,
# the initial velocity must be along the y-axis. Veloes are given by realistic speeds
# of the different planets
v_init = np.array([[0.0,30.0e3],[0.0,0.0],[0.0,12.8e3]])

#test result for the computed derivative for the values of p_init and v_init
dv_test = np.array([[-5.97953468e-03,  0.00000000e+00],
 [ 2.21144975e-07,  0.00000000e+00],
 [-2.12720889e-04,  0.00000000e+00]])
