In [8]:
import numpy as np

In [9]:
#Constant
beta = np.array([0, 0, 0, 0, 0])

# X0 = Z0
# X1 - 4X0 = Z1 + 2
# X2 - 2X0 = Z2 + 1
# X3 = Z3
# X4 - X1 - X2 - X3 = Z4
# Coefficient matrix A for the variables X (corresponding to equations above)
gamma = np.array([[1, 0, -1, 0],
                 [0, 1, 0, -2],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1],
                 [0, 0, -3, 1]], dtype=float) 

# Calcualte J
print("\nJ matrix: ")
J = (gamma @ gamma.T) / 1
print(J)

# covariance matrix, Sigma
print("\ncov matrix: ")
sigma = np.linalg.inv(J)
print(sigma)

# Calculate h vector
print("\nh vector: ")
h =  np.linalg.solve(gamma, beta)
print(h)

# mean vector, mu
print("\nmean vector: ")
mu = h.dot(np.linalg.inv(J))
print(mu)


J matrix: 
[[ 2.  0. -1.  0.  3.]
 [ 0.  5.  0. -2. -2.]
 [-1.  0.  1.  0. -3.]
 [ 0. -2.  0.  1.  1.]
 [ 3. -2. -3.  1. 10.]]

cov matrix: 


LinAlgError: Singular matrix

In [ ]:
p_d = [0.6, 0.4] 
p_i_given_d = [[0.1, 0.9], [0.1, 0.9]]
p_g_given_i_d = [
    [0.15, 0.4, 0.45],  
    [0.25, 0.05, 0.7],  
    [0.2, 0.1, 0.7],    
    [0.35, 0.3, 0.35]   
]

# Calculate the probability P(G = g1 | D = d1)
# We sum over both possible values of I
p_g1_given_d1 = sum(p_g_given_i_d[1][0] * p_i_given_d[1][i] for i in range(2))


### Factors in bayesian network

In [10]:
def phi_1(a,b):
    if a==1 and b==1:
        return 1
    elif a==1 and b==0:
        return 2
    else:
        return 3
    
def phi_2(c,d):
    if c==1 and d==1:
        return 10
    elif c==1 and d==0:
        return 15
    else:
        return 20
    
print(phi_1(1,1), phi_2(1,1))

1 10
